script/test: Formatting (indentation, etc.)

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -32,40 +32,38 @@ echo "-------------------------"
 #----------------------------------
 
 while [ $# -gt 0 ]; do
-  case "$1" in
+    case "$1" in
     --preset_name=*)
-      preset_name="${1#*=}"
-      ;;
+        preset_name="${1#*=}"
+        ;;
     --preset-name=*)
-      preset_name="${1#*=}"
-      ;;
+        preset_name="${1#*=}"
+        ;;
     --build_type=*)
-      build_type="${1#*=}"
-      ;;
+        build_type="${1#*=}"
+        ;;
     --build-type=*)
-      build_type="${1#*=}"
-      ;;
+        build_type="${1#*=}"
+        ;;
     --from=*)
-      from="${1#*=}"
-      ;;
+        from="${1#*=}"
+        ;;
     *)
-      printf "***************************\n"
-      printf "* Error: Invalid argument.*\n"
-      printf "***************************\n"
-      exit 1
-      ;;
-  esac
-  shift
+        printf "***************************\n"
+        printf "* Error: Invalid argument.*\n"
+        printf "***************************\n"
+        exit 1
+        ;;
+    esac
+    shift
 done
 
-if [ -z "$preset_name" ] && [ -n "$PRESET_NAME" ]
-then
-  preset_name="${PRESET_NAME}"
+if [ -z "$preset_name" ] && [ -n "$PRESET_NAME" ]; then
+    preset_name="${PRESET_NAME}"
 fi
 
-if [ -z "$build_type" ] && [ -n "$BUILD_TYPE" ]
-then
-  build_type="${BUILD_TYPE}"
+if [ -z "$build_type" ] && [ -n "$BUILD_TYPE" ]; then
+    build_type="${BUILD_TYPE}"
 fi
 
 baseDir=$(pwd)
